import React from "react";
import { Link } from "react-router-dom";
const repository = "https://github.com/ltuananh1105/Ecommerce-Customer-Churn-Analysis";
export default function ChurnDetail() {
 return <main className="editorial-page"><article className="editorial-shell editorial-narrow">
  <Link className="editorial-back" to="/project">← Back to Work</Link>
  <header className="editorial-intro reading-intro"><p className="editorial-eyebrow">Data Analysis Case Study</p><h1>E-Commerce Customer Churn &amp; Retention Analysis</h1><p>SQL · Power BI · Customer Analytics</p></header>
  <section className="editorial-section"><p className="editorial-eyebrow">01 / Overview</p><h2>Understanding where retention needs attention.</h2><p>An analysis of 5,630 customer records using SQL cleaning, feature engineering, and exploratory analysis to identify churn patterns and prioritize retention opportunities.</p></section>
  <section className="editorial-section"><p className="editorial-eyebrow">02 / Business Question</p><h2>Which customer groups warrant retention effort first?</h2><p>Establish the overall churn baseline, examine customer tenure and service complaints, and compare product and payment segments to guide targeted recommendations.</p></section>
  <section className="editorial-section"><p className="editorial-eyebrow">03 / Analysis Approach</p><ol><li>Clean the customer dataset in SQL Server and handle missing numerical values.</li><li>Engineer tenure and other analytical groupings.</li><li>Compare churn rates alongside segment sizes and the overall baseline.</li><li>Translate observed associations into retention recommendations, with limitations stated.</li></ol></section>
  <section className="editorial-section"><p className="editorial-eyebrow">04 / Key Findings</p><h2>Early tenure and complaints stand out.</h2><ul><li>Overall churn: <strong>16.84%</strong> — 948 of 5,630 customers.</li><li>First six months: <strong>32.42%</strong> churn — 697 of 2,150 customers.</li><li>Customers with complaints: <strong>31.67%</strong>, compared with <strong>10.93%</strong> without complaints.</li><li>Mobile Phone category: <strong>27.40%</strong>; Cash on Delivery: <strong>24.90%</strong>.</li></ul><p>These are associations, not causal effects. Mean imputation may reduce variation, and small segments require caution.</p></section>
  <section className="editorial-section"><p className="editorial-eyebrow">05 / Recommendations</p><ul><li>Prioritize onboarding and check-ins during the first six months.</li><li>Improve complaint resolution and follow up after resolution.</li><li>Investigate the Mobile Phone and Cash on Delivery customer journeys.</li></ul><p>These are proposed actions; measured retention improvements are not claimed.</p></section>
  <section className="editorial-section"><p className="editorial-eyebrow">06 / Evidence</p><h2>SQL analysis and documented results.</h2><p>The repository records the analysis queries and results. Power BI is listed in the project documentation; a dashboard file or screenshot was not available in the inspected source.</p><div className="evidence-placeholder"><span>Power BI dashboard — add real project screenshot</span><small>Real screenshot required · Placeholder, not evidence</small></div><a className="editorial-button" href={repository} target="_blank" rel="noopener noreferrer">View project source and results ↗</a></section>
 </article></main>;
}
